import template from '../../schemas/Defence_Facility_Visual_Handoff_Template.json';
import type { FacilityProductionHandoff } from '../../types/facilityProduction';

export function createFacilityPipelineHandoff(options:{active?:boolean}={}):FacilityProductionHandoff {
  const raw:any=JSON.parse(JSON.stringify(template));
  Object.assign(raw.facility,{official_name:'Hypothetical Documented Mountain Facility',facility_class:'historical underground defence facility',country_or_operator:'Documented public operator',construction_era:'Historical period',facility_status:options.active?'ACTIVE_PUBLICLY_DOCUMENTED':'DECLASSIFIED',public_location_name:'Public regional name',overall_visual_description:'Rock-integrated underground construction with documented concrete and ventilation elements',immutable_identity_features:['granite terrain envelope','documented tunnel portal proportions','weathered reinforced-concrete elements']});
  raw.historical_context.strategic_problem='Documented need for protected underground infrastructure';
  raw.historical_context.current_status=options.active?'Active and publicly documented with sensitivity restrictions':'Declassified historical site with abandoned remains';
  raw.site_dimensions_and_spatial_relations.important_spatial_relationships=['surface terrain connects conceptually to an access tunnel and then an underground chamber'];
  raw.site_dimensions_and_spatial_relations.terrain_relationships=['facility works are embedded within granite terrain'];
  raw.site_dimensions_and_spatial_relations.human_scale_reference='workers and excavators provide scale';
  raw.site_dimensions_and_spatial_relations.layout_claim_status='CONCEPTUAL_RELATIONSHIP_ONLY';
  Object.assign(raw.facility_modules[0],{module_name:'Facility-wide documented form',module_type:'FACILITY_WHOLE',verified_function:'Protected underground infrastructure',required_visible_features:['stable granite terrain envelope','documented portal proportions'],spatial_relationships:['surface terrain to tunnel to chamber, conceptual only'],forbidden_layout_claims:['exact room arrangement','hidden entrance position'],likely_wrong_substitutions:['generic missile silo','fictional command bunker']});
  const stageA=raw.construction_stages[0];
  Object.assign(stageA,{stage_name:'Site preparation and excavation',construction_function:'Expose and remove rock for supported underground works',stage_visual_summary:'Exposed granite, drilling, temporary access works, and managed spoil',environment_ids:['ENV_SITE_CONTEXT'],present_now:['exposed granite rock face','survey marks'],not_yet_built_or_installed:['completed tunnel','concrete lining','permanent ventilation equipment','operational chamber'],temporarily_exposed:['fresh rock face'],open_interfaces:['active excavation face'],temporary_works_present:['temporary access matting'],removed_material_or_spoil_state:'broken rock accumulates beside the excavation before haulage'});
  Object.assign(stageA.geometry_control,{required_visible_anchors:['exposed granite rock face'],minimum_visible_anchor_count:1,negative_constraints:['completed underground facility'],forbidden_transformations:['rock face becoming a finished tunnel mid-clip']});
  Object.assign(stageA.stage_actions[0],{action_description:'Drilling and excavation remove rock from the supported face',primary_subject:'construction drill',primary_action:'drill advances into exposed granite',allowed_minor_motion:'spoil falls below the face',required_tools_or_machinery:['rock drill','excavator'],required_worker_roles:['construction crew'],forbidden_actions:['combat blasting','weapon discharge']});
  stageA.visual_evidence.confirmed_visual_details=['temporary works beside excavated rock'];
  const stageB=JSON.parse(JSON.stringify(stageA));
  Object.assign(stageB,{stage_id:'STG_02',stage_number:2,stage_name:'Tunnelling and concrete lining',construction_function:'Advance the tunnel and install supported structural works',facility_state_code:'B',stage_visual_summary:'Open tunnel heading with temporary ground support, partial lining, and ventilation duct',environment_ids:['ENV_CONSTRUCTION_ZONE'],present_now:['open tunnel heading','temporary rock bolts','partial concrete lining'],not_yet_built_or_installed:['finished internal systems','completed operational chamber'],temporarily_exposed:['rock-to-lining interface'],open_interfaces:['unfinished tunnel heading'],temporary_works_present:['temporary ventilation duct'],removed_material_or_spoil_state:'muck moves from the heading toward haulage'});
  stageB.stage_actions[0].action_id='STG_02_ACT_01';
  stageB.stage_actions[0].action_description='Tunnel machinery advances while lining remains behind the face';
  stageB.continuity.forbidden_regressions=['untouched terrain presented as the current construction state','completed systems appearing before installation'];
  const stageC=JSON.parse(JSON.stringify(stageA));
  Object.assign(stageC,{stage_id:'STG_03',stage_number:3,stage_name:'Completed and abandoned remains',construction_function:'Document the surviving completed works and later abandonment',facility_state_code:'C',stage_visual_summary:'Weathered concrete remains and a sealed documented opening',environment_ids:['ENV_COMPLETED_FACILITY'],present_now:['weathered concrete remains','sealed documented opening'],not_yet_built_or_installed:[],temporarily_exposed:[],open_interfaces:[],temporary_works_present:[],removed_material_or_spoil_state:''});
  stageC.stage_actions[0].action_id='STG_03_ACT_01';
  stageC.stage_actions[0].action_description='Wind and water move across abandoned documented remains';
  raw.construction_stages=[stageA,stageB,stageC];
  Object.assign(raw.environments[0],{environment_name:'Granite mountain construction site',terrain:'granite mountain slope',weather_or_climate:'cold exposed weather',construction_features:['active rock face'],machinery:['rock drill','excavator'],temporary_works:['temporary access matting'],worker_roles:['construction crew'],forbidden_elements:['current guard posts','hidden entrance reconstruction']});
  Object.assign(raw.environments[1],{environment_name:'Underground tunnel construction zone',terrain:'exposed granite underground',construction_features:['open tunnel heading','partial lining'],machinery:['tunnel drill','loader','spoil conveyor'],temporary_works:['rock bolts','temporary ventilation duct'],worker_roles:['tunnel crew'],forbidden_elements:['finished operational chamber','current security layout']});
  Object.assign(raw.environments[2],{environment_name:'Abandoned documented remains',construction_features:['weathered concrete','sealed opening'],forbidden_elements:['pristine active facility','guard patrol']});
  const chapter=raw.visual_story_plan.chapters[0],base=chapter.visual_beats[0];
  Object.assign(chapter,{chapter_name:'Terrain, construction, evidence, and fate',narrative_goal:'Explain how documented terrain, excavation, tunnelling, environmental limits, and abandonment shaped the facility',applicable_construction_stage_ids:['STG_01','STG_02','STG_03']});
  const beat=(id:string,family:string,story:string,purpose:string,terms:string[],stage:string,extra:any={})=>({...JSON.parse(JSON.stringify(base)),beat_id:id,beat_order:0,beat_name:purpose,visual_family:family,story_function:story,narrative_purpose:purpose,semantic_alignment_terms:terms,applicable_stage_ids:[stage],environment_ids:[stage==='STG_01'?'ENV_SITE_CONTEXT':stage==='STG_02'?'ENV_CONSTRUCTION_ZONE':'ENV_COMPLETED_FACILITY'],facility_visibility:family==='TERRAIN_CONTEXT'||family==='ARCHIVAL_REFERENCE'?'NONE':'PARTIAL',required_facility_state_code:stage==='STG_01'?'A':stage==='STG_02'?'B':'C',facility_claim_status:'GENERIC_NON_IDENTIFYING_VISUAL',layout_claim_status:'UNKNOWN',reference_asset_ids:[],preferred_media_routes:['GENERATED_T2V'],generation_permission:'T2V_ALLOWED',exact_site_claim_allowed:false,exact_layout_claim_allowed:false,must_show:[purpose],must_not_show:['invented current access route','current security procedure'],continuity_requirements:['preserve assigned construction state'],negative_constraints:['guard posts','surveillance blind spots','vulnerability analysis'],...extra});
  chapter.visual_beats=[
    beat('TERRAIN','TERRAIN_CONTEXT','ESTABLISH_LOCATION','Granite mountain terrain context',['mountain','granite','terrain'],'STG_01'),
    beat('EXCAVATION','EXCAVATION_AND_BLASTING','INTRODUCE_CONSTRUCTION_PROBLEM','Drilling and controlled construction blasting remove rock',['drilling','blasting','excavation','spoil'],'STG_01'),
    beat('TUNNEL','TUNNELING','EXPLAIN_PROCESS','Tunnel heading advances with temporary ground support',['tunnel','rock bolts','shotcrete'],'STG_02'),
    beat('CONCRETE','CONCRETE_AND_LINING','EXPLAIN_PROCESS','Partial reinforced-concrete lining follows excavation',['concrete','lining','waterproofing'],'STG_02'),
    beat('ENVIRONMENT','ENVIRONMENTAL_CHALLENGE','SHOW_FAILURE_OR_LIMIT','Groundwater and cracking constrain the works',['groundwater','leak','cracking'],'STG_02'),
    beat('CUTAWAY','CUTAWAY_RECONSTRUCTION','EXPLAIN_SPATIAL_RELATIONSHIP','Conceptual surface to tunnel to chamber relationship',['surface','tunnel','chamber','conceptual'],'STG_02',{layout_claim_status:'CONCEPTUAL_RELATIONSHIP_ONLY'}),
    beat('ARCHIVE','ARCHIVAL_REFERENCE','PROVIDE_HISTORICAL_CONTEXT','Declassified archival construction photograph',['archive','declassified','photograph'],'STG_01',{reference_asset_ids:['REF_001'],preferred_media_routes:['ARCHIVAL_IMAGE'],generation_permission:'REFERENCE_REQUIRED'}),
    beat('REMAINS','ABANDONMENT_OR_REMAINS','RESOLVE_FATE','Abandoned weathered facility remains',['abandoned','remains','today'],'STG_03'),
  ].map((item:any,index:number)=>({...item,beat_order:index+1}));
  Object.assign(raw.reference_assets[0],{facility_or_module:'FACILITY_WHOLE',construction_or_operational_state:'Historical construction',view_angle_or_document_scope:'Public archival construction view',publisher_or_owner:'Hypothetical public archive',date_or_event:'Historical construction period',facility_claim_status:'GENERIC_NON_IDENTIFYING_VISUAL',layout_claim_status:'UNKNOWN',visible_or_documented_features:['exposed rock face','temporary works'],allowed_usage:['historical evidence'],forbidden_usage:['exact layout claim','current security inference'],recommended_media_routes:['ARCHIVAL_IMAGE'],confidence:'CORROBORATED'});
  return raw as FacilityProductionHandoff;
}
